
VERSION := 0.0.1
OS ?= $(shell uname -s)
CWARNFLAGS := -Wall -Wold-style-cast -Wundef -Wsign-compare -Wconversion -Wpointer-arith -pedantic
CFLAGS := $(CWARNFLAGS) -g -O2 

#prefix := /usr


SRC:=$(wildcard *.c)
STATIC_OBJ := $(SRC:.c=.o)
SHARD_OBJ  := $(SRC:.c=.lo)

STATIC_LIB :=libtsmux.a

ifeq ($(OS), Darwin)
  SHARED_LIB_BASE := libtsmux.dylib
  SHARED_LIB_VERSIONED := libtsmux.$(VERSION).dylib
  override LDFLAGS += -dynamiclib -single_module -install_name $(SHARED_LIB_VERSIONED) -fPIC
  LDLIBS := -lpthread
endif
  
  
RESULT_DIR := ./lib/

.PHONY: all build-static build-shared clean distclean
all: build-static build-shared

build-static: $(RESULT_DIR)$(STATIC_LIB)
build-shared: $(RESULT_DIR)$(SHARED_LIB_VERSIONED)

clean:
	$(RM) $(STATIC_OBJ)
ifneq ($(OS), Windows)
	$(RM) $(SHARED_OBJ)
endif

distclean: clean cleandeps
	$(RM) $(RESULT_DIR)$(STATIC_LIB)
	$(RM) $(RESULT_DIR)$(SHARED_LIB_VERSIONED)

ifneq ($(OS),Windows)
INSTALL := install
INSTALL_DATA := $(INSTALL) -m 644

.PHONY: install install-static install-shared
install: install-static install-shared

install-static: $(RESULT_DIR)$(STATIC_LIB)
	mkdir -p $(prefix)/lib
	$(INSTALL_DATA) $(RESULT_DIR)$(STATIC_LIB) $(prefix)/lib

install-shared: $(RESULT_DIR)$(SHARED_LIB_VERSIONED)
	mkdir -p $(prefix)/lib
	$(INSTALL_DATA) $(RESULT_DIR)$(SHARED_LIB_VERSIONED) $(prefix)/lib
	cd $(prefix)/lib; ln -s $(SHARED_LIB_VERSIONED) $(SHARED_LIB_BASE)

%.lo : %.c
	$(CC) -c $(CFLAGS) -fPIC -o $@ $<

$(RESULT_DIR)$(SHARED_LIB_VERSIONED): $(SHARED_OBJ)
else
$(RESULT_DIR)$(SHARED_LIB_VERSIONED): $(STATIC_OBJ)
endif
	$(CC) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(RESULT_DIR)$(STATIC_LIB): $(STATIC_OBJ)
	$(AR) $(ARFLAGS) $@ $^  
	
	
.PHONY: cleandeps

ifneq ($(OS),Windows)

.static-dep/%.dep: %.c
	@mkdir -p $(dir $@)
	$(CC) -MM -MT $(patsubst %.c,%.o,$<) $(CFLAGS) $< > $@

.shared-dep/%.dep: %.c
	@mkdir -p $(dir $@)
	$(CC) -MM -MT $(patsubst %.c,%.lo,$<) $(CFLAGS) $< > $@

ifneq ($(MAKECMDGOALS),clean)
	ifneq ($(MAKECMDGOALS),distclean)
		-include $(addprefix .static-dep/,$(SRC:.c=.dep))
		-include $(addprefix .shared-dep/,$(SRC:.c=.dep))
	endif
endif

cleandeps:
	$(RM) -R .static-dep
	$(RM) -R .shared-dep

else
cleandeps:
endif

